[package]
name = "codecrafters-dns-server"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.85"

[dependencies]
bytes = "1"
tokio = { version = "1", features = ["full"] }
