[package]
name = "codecrafters-dns-server"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.85"

[dependencies]
nom = "8.0.0"
zerocopy = "0.8.24"
tokio = { version = "1", features = ["full"] }
